Update 02-Run_Unit_Test.yaml

diff --git a/.github/workflows/02-Run_Unit_Test.yaml b/.github/workflows/02-Run_Unit_Test.yaml
--- a/.github/workflows/02-Run_Unit_Test.yaml
+++ b/.github/workflows/02-Run_Unit_Test.yaml
@@ -61,17 +61,52 @@ jobs:
                 }' \
             https://api.github.com/repos/${{ env.REPO_B_OWNER }}/${{ env.REPO_B_NAME }}/actions/workflows/02-Run_Unit_Test.yaml/dispatches)
 
-          echo "Response: $response"
-
-      - name: Check if Workflow ran successfully
-        run: |
+          echo "Triggered workflow: $response"
           if echo "$response" | grep -q '"message": "Not Found"'; then
-            echo "Error: Workflow or repository not found."
+            echo "Error: Workflow or repository not found. Please check the repository name, workflow file name, and branch name."
             exit 1
           fi
-          if echo "$response" | grep -q '"status": "completed"'; then
-            echo "Workflow B ran successfully!"
-          else
-            echo "Workflow B failed to start or complete."
-            exit 1
-          fi
+
+
+      - name: Wait for Check-Time Workflow to Complete
+        id: wait
+        env:
+          TIMEOUT: 1800
+        run: |
+          sleep 30
+          run_id=$(curl -s \
+            -H "Accept: application/vnd.github.v3+json" \
+            -H "Authorization: token ${{ secrets.SILABS_THIEUVU_PAT }}" \
+            https://api.github.com/repos/SiliconLabsInternal/DevS-SQA/actions/runs \
+            | jq '.workflow_runs[] | select(.name=="02-Run_Unit_Test") | .id' | head -n 1)
+          echo "Run ID: $run_id"
+          start_time=$(date +%s)
+          while true; do
+            current_time=$(date +%s)
+            elapsed_time=$((current_time - start_time))
+            if [ $elapsed_time -ge $TIMEOUT ]; then
+              echo "Error: Workflow did not complete within $((TIMEOUT / 60)) minutes."
+              exit 1
+            fi
+            status=$(curl -s \
+              -H "Accept: application/vnd.github.v3+json" \
+              -H "Authorization: token ${{ secrets.SILABS_THIEUVU_PAT }}" \
+              https://api.github.com/repos/SiliconLabsInternal/DevS-SQA/actions/runs/$run_id \
+              | jq -r '.status')
+            conclusion=$(curl -s \
+              -H "Accept: application/vnd.github.v3+json" \
+              -H "Authorization: token ${{ secrets.SILABS_THIEUVU_PAT }}" \
+              https://api.github.com/repos/SiliconLabsInternal/DevS-SQA/actions/runs/$run_id \
+              | jq -r '.conclusion')
+            echo "Status: $status, Conclusion: $conclusion"
+            if [[ "$status" == "completed" ]]; then
+              if [[ "$conclusion" == "success" ]]; then
+                echo "Workflow completed successfully."
+                exit 0
+              else
+                echo "Workflow failed."
+                exit 1
+              fi
+            fi
+            sleep 30
+          done
