Update 03-Run_Integration_Test.yaml

diff --git a/.github/workflows/03-Run_Integration_Test.yaml b/.github/workflows/03-Run_Integration_Test.yaml
--- a/.github/workflows/03-Run_Integration_Test.yaml
+++ b/.github/workflows/03-Run_Integration_Test.yaml
@@ -38,34 +38,34 @@ on:
         type: string
         default: 'DS_SQA_HN_01'
 env:
-  REPO_BRANCH_BUILD: ${{ github.head_ref || github.ref_name }}
-  REPO_NAME: ${{ github.event.repository.name }}
-  JLINK_PATH: /opt/SEGGER/JLink/libjlinkarm.so
-  SDK_PATH_RUN: /home/sqa/SimplicityStudio/SDKs/gecko_sdk
-  AM_CORRETTO_17: https://corretto.aws/downloads/latest/amazon-corretto-17-x64-linux-jdk.tar.gz
-  SLC_CLI_URL: https://www.silabs.com/documents/login/software/slc_cli_linux.zip
-  COMMANDER_URL: https://www.silabs.com/documents/login/software/SimplicityCommander-Linux.zip
-  GCC_URL: https://developer.arm.com/-/media/Files/downloads/gnu/12.2.rel1/binrel/arm-gnu-toolchain-12.2.rel1-x86_64-arm-none-eabi.tar.xz
-  SIM_REPO: https://github.com/SiliconLabs/simplicity_sdk.git
-  GECKO_SDK_REPO: https://github.com/SiliconLabs/gecko_sdk.git
-  SDK_VER: v4.4.2
-  JLINK_SEGGER_URL: https://www.segger.com/downloads/jlink/JLink_Linux_x86_64.tgz
-  TASK: gen-only
-  REPO_BRANCH_RUN: main    
-  BOARD_NAME_MG12: brd4161a
-  BOARD_NAME_MG24: brd4187c
-  ADAPTER_SN_MG12: ${{ github.event.inputs.ADAPTER_SN_MG12 }} #440189400
-  ADAPTER_SN_MG24: ${{ github.event.inputs.ADAPTER_SN_MG24 }} #440133193
-  HOST_IP: 192.168.1.69
-  TOOL_DIRS_BUILD: arm-gnu-toolchain-12.2.rel1-x86_64-arm-none-eabi/bin
-  COMPILER: GCC
-  TOOL_CHAINS: GCC
-  COMPONENT: all
-  CHIP_MG12: EFR32MG12
-  CHIP_MG24: EFR32MG24BXXXF1536
-  TOOL_DIRS_RUN: /home/sqa/SimplicityStudio-5/SimplicityStudio_v5/developer/toolchains/gnu_arm/12.2.rel1_2023.7/bin
-  START_ADDR_FLASH_M12: 0x0000000
-  START_ADDR_FLASH_M24: 0x8000000
+    REPO_BRANCH_BUILD: ${{ github.head_ref || github.ref_name }}
+    REPO_NAME: ${{ github.event.repository.name }}
+    JLINK_PATH: /opt/SEGGER/JLink/libjlinkarm.so
+    SDK_PATH_RUN: /home/sqa/SimplicityStudio/SDKs/gecko_sdk
+    AM_CORRETTO_17: https://corretto.aws/downloads/latest/amazon-corretto-17-x64-linux-jdk.tar.gz
+    SLC_CLI_URL: https://www.silabs.com/documents/login/software/slc_cli_linux.zip
+    COMMANDER_URL: https://www.silabs.com/documents/login/software/SimplicityCommander-Linux.zip
+    GCC_URL: https://developer.arm.com/-/media/Files/downloads/gnu/12.2.rel1/binrel/arm-gnu-toolchain-12.2.rel1-x86_64-arm-none-eabi.tar.xz
+    SIM_REPO: https://github.com/SiliconLabs/simplicity_sdk.git
+    GECKO_SDK_REPO: https://github.com/SiliconLabs/gecko_sdk.git
+    SDK_VER: v4.4.2
+    JLINK_SEGGER_URL: https://www.segger.com/downloads/jlink/JLink_Linux_x86_64.tgz
+    TASK: gen-only
+    REPO_BRANCH_RUN: main    
+    BOARD_NAME_MG12: brd4161a
+    BOARD_NAME_MG24: brd4187c
+    ADAPTER_SN_MG12: ${{ github.event.inputs.ADAPTER_SN_MG12 }} #440189400
+    ADAPTER_SN_MG24: ${{ github.event.inputs.ADAPTER_SN_MG24 }} #440133193
+    HOST_IP: 192.168.1.69
+    TOOL_DIRS_BUILD: arm-gnu-toolchain-12.2.rel1-x86_64-arm-none-eabi/bin
+    COMPILER: GCC
+    TOOL_CHAINS: GCC
+    COMPONENT: all
+    CHIP_MG12: EFR32MG12
+    CHIP_MG24: EFR32MG24BXXXF1536
+    TOOL_DIRS_RUN: /home/sqa/SimplicityStudio-5/SimplicityStudio_v5/developer/toolchains/gnu_arm/12.2.rel1_2023.7/bin
+    START_ADDR_FLASH_M12: 0x0000000
+    START_ADDR_FLASH_M24: 0x8000000
 jobs:
   job1:
     name: Generate Firmware
@@ -82,22 +82,22 @@ jobs:
         echo "Current directory: $PWD"
     - name: Check Branch Input
       run: |
-            if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
-              if [ -z "${{ github.event.inputs.Contribute_branch }}" ]; then
-                echo "Branch input is required for manual trigger."
-                exit 1
-              else
-                echo "REPO_BRANCH_BUILD=${{ github.event.inputs.Contribute_branch }}">> $GITHUB_ENV
-              fi
-            fi              
+        if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
+          if [ -z "${{ github.event.inputs.Contribute_branch }}" ]; then
+            echo "Branch input is required for manual trigger."
+            exit 1
+          else
+            echo "REPO_BRANCH_BUILD=${{ github.event.inputs.Contribute_branch }}">> $GITHUB_ENV
+          fi
+        fi              
     - name: Checkout
       uses: actions/checkout@v4.1.7
       with:
         ref: "${{ github.event_name == 'workflow_dispatch' && github.event.inputs.Contribute_branch || github.ref }}"
     - name: Log Current Branch and Commit
       run: |
-          echo "Current branch: $(git rev-parse --abbrev-ref HEAD)"
-          echo "Current commit: $(git rev-parse HEAD)" 
+        echo "Current branch: $(git rev-parse --abbrev-ref HEAD)"
+        echo "Current commit: $(git rev-parse HEAD)" 
     - name: Install Simplicity SDK
       run: |
         mkdir simplicity_studio
@@ -284,22 +284,22 @@ jobs:
         mkdir ${{ github.workspace }}
     - name: Check Branch Input
       run: |
-            if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
-              if [ -z "${{ github.event.inputs.Validate_branch }}" ]; then
-                echo "Validate branch input is required for manual trigger."
-                exit 1
-              else
-                echo "REPO_BRANCH_RUN=${{ github.event.inputs.Validate_branch }}">> $GITHUB_ENV
-              fi
-            fi              
+        if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
+          if [ -z "${{ github.event.inputs.Validate_branch }}" ]; then
+            echo "Validate branch input is required for manual trigger."
+            exit 1
+          else
+            echo "REPO_BRANCH_RUN=${{ github.event.inputs.Validate_branch }}">> $GITHUB_ENV
+          fi
+        fi              
     - name: Checkout
       uses: actions/checkout@v4.1.7
       with:
         ref: "${{ github.event_name == 'workflow_dispatch' && github.event.inputs.Validate_branch || github.ref }}" 
     - name: Log Current Branch and Commit
       run: |
-          echo "Current branch: $(git rev-parse --abbrev-ref HEAD)"
-          echo "Current commit: $(git rev-parse HEAD)" 
+        echo "Current branch: $(git rev-parse --abbrev-ref HEAD)"
+        echo "Current commit: $(git rev-parse HEAD)" 
     - name: Create build folder
       run: |
         make prepare
@@ -310,52 +310,52 @@ jobs:
         #sudo apt-get install jq -y
     - name: Download output for MG12 from Job 1
       run: |
-          export PAT="${{ secrets.SILABS_THIEUVU_PAT}}"  
-          export REPO_OWNER="SiliconLabsSoftware"
-          export REPO_NAME="IEC60730-Library"
-          export RUN_ID="${{ github.run_id }}" 
-          export ARTIFACT_NAME="firmware_mg12_gcc"  
-          
-          ARTIFACT_URL=$(curl -s -H "Authorization: token $PAT" \
-            "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/actions/runs/$RUN_ID/artifacts" | \
-            jq -r ".artifacts[] | select(.name==\"$ARTIFACT_NAME\") | .archive_download_url")
-          if [ -z "$ARTIFACT_URL" ]; then
-            echo "Artifact not found for run ID $RUN_ID."
-            exit 1
-          fi
-          curl -L -o firmware_mg12_gcc.zip -H "Authorization: token $PAT" "$ARTIFACT_URL"
-          if [ $? -eq 0 ] && [ -f "firmware_mg12_gcc.zip" ]; then
-            echo "Download successful"
-            mv firmware_mg12_gcc.zip ./build/
-            unzip ./build/firmware_mg12_gcc.zip -d ./build/
-            ls -R
-          else
-            echo "Download failed"
-            exit 1
-          fi
+        export PAT="${{ secrets.SILABS_THIEUVU_PAT}}"  
+        export REPO_OWNER="SiliconLabsSoftware"
+        export REPO_NAME="IEC60730-Library"
+        export RUN_ID="${{ github.run_id }}" 
+        export ARTIFACT_NAME="firmware_mg12_gcc"  
+        
+        ARTIFACT_URL=$(curl -s -H "Authorization: token $PAT" \
+          "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/actions/runs/$RUN_ID/artifacts" | \
+          jq -r ".artifacts[] | select(.name==\"$ARTIFACT_NAME\") | .archive_download_url")
+        if [ -z "$ARTIFACT_URL" ]; then
+          echo "Artifact not found for run ID $RUN_ID."
+          exit 1
+        fi
+        curl -L -o firmware_mg12_gcc.zip -H "Authorization: token $PAT" "$ARTIFACT_URL"
+        if [ $? -eq 0 ] && [ -f "firmware_mg12_gcc.zip" ]; then
+          echo "Download successful"
+          mv firmware_mg12_gcc.zip ./build/
+          unzip ./build/firmware_mg12_gcc.zip -d ./build/
+          ls -R
+        else
+          echo "Download failed"
+          exit 1
+        fi
           
     - name: Download output for MG24 from Job 1
       run: |
-          export PAT="${{ secrets.SILABS_THIEUVU_PAT}}"  
-          export REPO_OWNER="SiliconLabsSoftware"
-          export REPO_NAME="IEC60730-Library"
-          export RUN_ID="${{ github.run_id }}" 
-          export ARTIFACT_NAME="firmware_mg24_gcc"  
-          
-          ARTIFACT_URL=$(curl -s -H "Authorization: token $PAT" \
-            "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/actions/runs/$RUN_ID/artifacts" | \
-            jq -r ".artifacts[] | select(.name==\"$ARTIFACT_NAME\") | .archive_download_url")
-          if [ -z "$ARTIFACT_URL" ]; then
-            echo "Artifact not found for run ID $RUN_ID."
-            exit 1
-          fi
-          curl -L -o firmware_mg24_gcc.zip -H "Authorization: token $PAT" "$ARTIFACT_URL"
-          if [ $? -eq 0 ] && [ -f "firmware_mg24_gcc.zip" ]; then
-            echo "Download successful"
-          else
-            echo "Download failed"
-            exit 1
-          fi
+        export PAT="${{ secrets.SILABS_THIEUVU_PAT}}"  
+        export REPO_OWNER="SiliconLabsSoftware"
+        export REPO_NAME="IEC60730-Library"
+        export RUN_ID="${{ github.run_id }}" 
+        export ARTIFACT_NAME="firmware_mg24_gcc"  
+        
+        ARTIFACT_URL=$(curl -s -H "Authorization: token $PAT" \
+          "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/actions/runs/$RUN_ID/artifacts" | \
+          jq -r ".artifacts[] | select(.name==\"$ARTIFACT_NAME\") | .archive_download_url")
+        if [ -z "$ARTIFACT_URL" ]; then
+          echo "Artifact not found for run ID $RUN_ID."
+          exit 1
+        fi
+        curl -L -o firmware_mg24_gcc.zip -H "Authorization: token $PAT" "$ARTIFACT_URL"
+        if [ $? -eq 0 ] && [ -f "firmware_mg24_gcc.zip" ]; then
+          echo "Download successful"
+        else
+          echo "Download failed"
+          exit 1
+        fi
     - name: Install GCC
       run: |
         wget $GCC_URL
@@ -402,17 +402,15 @@ jobs:
         echo "Run unit test for MG24"
         cd ${{ github.workspace }}
         ls -la
-        # rm -rf build
         make prepare
         mv firmware_mg24_gcc.zip ./build/
         unzip ./build/firmware_mg24_gcc.zip -d ./build/
-        ls -R
         cd build
         cmake --toolchain ../cmake/toolchain.cmake .. -DENABLE_INTEGRATION_TESTING=ON -DBOARD_NAME=$BOARD_NAME_MG24
         make integration_test_info -j4
         cd ../test
-        if [ -z "${{ github.event.inputs.ADAPTER_SN_MG12 }}" ]; then
-            ADAPTER_SN_MG12=440189400
+        if [ -z "${{ github.event.inputs.ADAPTER_SN_MG24 }}" ]; then
+            ADAPTER_SN_MG24=440133193
         fi
         if [ -z "${{ github.event.inputs.HOST_IP_MG24 }}" ]; then
             HOST_IP_MG24=192.168.1.69
